function changeLang(lang) {
  const t = translations[lang];

  if (!t) return; // dil yoksa işlemi durdur

  document.title = t.title;

  document.getElementById("navHome").textContent = t.navHome;
  document.getElementById("navJapan").textContent = t.navJapan;
  document.getElementById("navLearn").textContent = t.navLearn;

  document.getElementById("homeTitle").textContent = t.homeTitle;
  document.getElementById("homeTitle2").textContent = t.homeTitle2;

 


}
function changeLang(lang) {
  const t = translations[lang];
  if (!t) return;

  document.title = t.title;

 const ids = [
  "title", "navHome", "navJapan", "navLearn",
  "homeTitle", "homeTitle2", "homeText",
  "japanTitle", "japanText",
  "yasamTitle", "yasamText",
  "kulturTitle", "kulturText",
  "festivalTitle", "festivalText",
  "ulasimTitle", "ulasimText",
  "egitimTitle", "egitimText",
  "linkYasam", "linkKultur", "linkFestival", "linkUlasim", "linkEgitim",
  "author1_name", "author1_bio", "author1_book", "author1_desc",
  "author2_name", "author2_bio", "author2_book", "author2_desc",
  "author3_name", "author3_bio", "author3_book", "author3_desc",
  "author4_name", "author4_bio", "author4_book", "author4_desc",
  "author5_name", "author5_bio", "author5_book", "author5_desc",
  "animeTitle", "animeIntro",
  "anime0Title", "anime0Desc",
  "anime1Title", "anime1Desc",
  "anime2Title", "anime2Desc",
  "anime3Title", "anime3Desc",
  "anime4Title", "anime4Desc",
   "musicTitle", "musicIntro",
  "music0Title", "music0Genre", "music0Desc",
  "music1Title", "music1Genre", "music1Desc",
  "music2Title", "music2Genre", "music2Desc",
  "music3Title", "music3Genre", "music3Desc",
  "music4Title", "music4Genre", "music4Desc",
  "dogaTitle","dogaText","teknolojiTitle","teknolojiText",
  "sanatTitle","sanatText","linkDoga","linkTeknoloji","linkSanat",
  "random1","random1T","random2","random2T","random3",
  "random3T","random4","random4T","random5","random5T",
  "random6","random6T","random7","random7T","random8","random8T",
  "learnTitle","learnText", "mean1",
  "mean2",
  "mean3",
  "mean4",
  "mean5",
  "mean6",
  "mean7",
  "mean8",
  "mean9",
  "mean10",
  "mean11",
  "mean12",
  "mean13",
  "mean14",
  "mean15",
  "mean16B",
  "mean17B",
  "mean18B",
  "mean19",
  "mean20",
  "mean21",
  "mean22",
  "mean23",
  "mean24",
  "mean25",
  "mean26",
  "mean27B",
  "mean28B",
  "mean29",
  "mean30",
  "mean31",
  "mean32",
  "mean33",
  "mean34",
  "mean35",
  "mean36",
  "mean37B",
  "mean38B",
  "mean39",
  "mean40",
  "mean41",
  "mean42",
  "mean43",
  "mean44",
  "mean45",
  "mean46",
  "mean47",
  "mean48",
  "mean49B",
  "mean50B",
  "mean51",
  "mean52",
  "mean53",
  "mean54",
  "mean55",
  "mean56",
  "mean57",
  "mean58",
  "mean59B",
  "mean60B", "grammarBox",
  "grammarBox-title",
  "grammarNote1",
  "grammarNote2",
  "grammarNote3",
  "grammarBox2",
  "grammarBox2-title",
  "grammarParticlesList",
  "particleHa",
  "particleHa-example",
  "particleWo",
  "particleWo-example",
  "particleNi",
  "particleNi-example",
  "grammarBox3",
  "grammarBox3-title",
  "positiveNegativeList",
  "exprSuki",
  "exprSuki-example",
  "exprKirai",
  "exprKirai-example",
  "exprArimasen",
  "exprArimasen-example",
  "exprArimasu",
  "exprArimasu-example",
  "conjunctionBox",
  "conjunctionBox-title",
  "conjunctionTable",
  "col-word",
  "col-reading",
  "col-meaning",
  "col-example",
  "conj1",
  "conj1-word",
  "conj1-reading",
  "conj1-meaning",
  "conj1-example",
  "conj2",
  "conj2-word",
  "conj2-reading",
  "conj2-meaning",
  "conj2-example",
  "conj3",
  "conj3-word",
  "conj3-reading",
  "conj3-meaning",
  "conj3-example",
  "conj4",
  "conj4-word",
  "conj4-reading",
  "conj4-meaning",
  "conj4-example",
  "conj5",
  "conj5-word",
  "conj5-reading",
  "conj5-meaning",
  "conj5-example", "linkSelam",
"linkTan",
"linkSayi",
"linkYer",
"linkAlis",
"linkFiil",
"linkGramer",
"linkPart",
"linkOlumlu",
"linkBag"

  
];


  ids.forEach(id => {
    const el = document.getElementById(id);
    if (el && t[id]) {
      el.textContent = t[id];
    }
  });
}

const translations = {
  tr: {
    title: "SakuraPages",
    navHome: "Anasayfa",
    navJapan: "Japonya",
    navLearn: "Japonca",

    homeTitle: "Anasayfa",
    homeTitle2: "Sakura ağaçlarının gölgesinde Japonya’yı keşfetmeye hazır mısın?",
    homeText: "Sakura Pages'e hoş geldiniz. Arkanıza yaslanın ve Japonya hakkında bilgilenmenin, Japonca hakkında fikir sahibi olmanın tadını çıkarın. Sizi Japonya'ya doğru bir yolculuğa çıkarıyoruz. İster Japonya bölümünden Japonya hakkında bilgiler öğrenin, isterseniz Japonca kısmından günlük konuşmalar hakkında fikir sahibi olabileceğiniz bir dil yolculuğuna çıkın. Sakura Pages her iki konuda da içerikleriyle sizi desteklemeye hazır. Öyleyse, başlayalım mı?",

    
    japanTitle: "Japonya",
    japanText: "Japonya, Doğu Asya’da Pasifik Okyanusu üzerinde yer alan bir ada ülkesidir. Dört büyük ada—Honshu, Hokkaido, Kyushu ve Shikoku—ve binlerce küçük adadan oluşur. Başkenti Tokyo’dur ve yaklaşık 125 milyonluk nüfusuyla dünyanın en kalabalık ülkelerinden biridir. Resmi dili Japonca olan Japonya’da, hiragana, katakana ve kanji olmak üzere üç farklı alfabe sistemi kullanılır. Ülke, anayasal monarşiyle yönetilir ve İmparator, kültürel bir sembol olarak varlığını sürdürürJaponya, zengin kültürüyle geleneksel ve modern yaşamı uyum içinde birleştirir. Antik tapınaklardan yüksek teknolojiye, çay seremonilerinden anime ve mangaya kadar birçok özgün öğeye ev sahipliği yapar. Otomotiv, elektronik, oyun ve robotik gibi alanlarda dünyanın önde gelen ülkelerinden biridir.Doğal güzellikleriyle de öne çıkan Japonya; aktif yanardağları, sık yaşanan depremleri ve dört mevsimi hissedebileceğiniz iklimiyle dikkat çeker. Fuji Dağı, ülkenin simgesi haline gelmiştir. Kuzeydeki karla kaplı Hokkaido’dan güneydeki tropik Okinawa’ya kadar çeşitli doğa manzaraları sunar.Japon mutfağı ise dünyaca ünlüdür. Sushi, ramen, tempura ve matcha gibi lezzetler hem yerel halkın hem de ziyaretçilerin favorilerindendir. Temiz şehirleri, güvenli sokakları ve saygılı insanlarıyla Japonya, keşfetmeye değer eşsiz bir kültür ve yaşam tarzı sunar.",
    yasamTitle: "Japonya’da Yaşam",
    yasamText:"Japonya, modern yaşamın hızını geleneksel değerlerle dengeleyen benzersiz bir ülkedir. Şehirlerde yaşam oldukça yoğun ve sistemlidir; özellikle Tokyo, Osaka ve Kyoto gibi büyük şehirlerde hayat hızlı akar. Toplu taşıma dakikliğiyle ünlüdür ve insanlar genel olarak disiplinli, saygılı ve toplumsal kurallara önem veren bir yaşam tarzı benimser. Yürürken telefonla konuşmamak, toplu taşıma araçlarında sessiz olmak gibi kurallar, günlük yaşamın bir parçasıdır.Konutlar genellikle kompakt ve fonksiyoneldir; şehir merkezlerinde küçük daireler yaygındır. Japonya’da yaşam pahalı olabilir, ancak sağlık hizmetleri, güvenlik, temizlik ve teknolojiye erişim gibi konularda oldukça yüksek bir yaşam standardı sunar. Ayrıca Japonya’nın her köşesi, mevsimlerin belirginliğiyle farklı bir güzellik taşır. İlkbaharda sakura çiçekleriyle kaplanan sokaklar, sonbaharda kızıl yapraklarla dolan parklar yaşamın bir parçasıdır.Japonlar, sosyal hayatta nezakete ve uyuma büyük önem verir. İş ortamında hiyerarşi ve grup uyumu öne çıkarken, arkadaşlık ilişkilerinde karşılıklı anlayış ve mesafe korunur. Ayrıca Japonya'da yaşam süresi oldukça yüksektir; sağlıklı beslenme alışkanlıkları ve aktif yaşam tarzı bunda etkilidir.",
    kulturTitle: "Geleneksel Kültür",
    kulturText: "Japon kültürü, zarafet ve sadeliğin öne çıktığı birçok geleneksel ögeye sahiptir. Bu ögelerden biri olan kimono, hem günlük yaşamda hem de özel günlerde giyilen geleneksel bir giysidir. Kumaşın rengine, desenine ve dokusuna göre farklı anlamlar taşır; düğünlerde beyaz ve altın tonları, yaz festivallerinde ise canlı renkli yazlık versiyonu olan yukata tercih edilir.Bir diğer önemli kültürel gelenek olan çay seremonisi (茶道 / sadō), sadece çay içmekten öte bir felsefeyi temsil eder. Ev sahibi, misafire özenle hazırlanmış matcha (yeşil toz çay) sunarken, her hareket belirli bir düzen ve sakinlikle yapılır. Bu ritüel, sadelik, saygı, uyum ve huzur gibi değerleri ön plana çıkarır.İkebana (生け花) ise çiçek düzenleme sanatıdır. Batı’daki çiçek aranjmanlarından farklı olarak ikebana’da doğanın ruhunu ve mevsimsel geçişleri yansıtmak esastır. Dalların yönü, boşlukların kullanımı ve renk dengesiyle oluşturulan kompozisyon, adeta bir meditasyon biçimidir.Bu üç geleneksel sanat, Japonya'nın doğaya, estetiğe ve içsel dengeye verdiği önemin birer yansımasıdır. Modern Japonya'da hâlâ saygı gören bu uygulamalar, geçmişin zarafetini günümüze taşımaya devam etmektedir..",
    festivalTitle: "Festivaller",
    festivalText: "Japonya’da festivaller, hem dini geleneklerin hem de mevsimsel geçişlerin kutlandığı, toplumun bir araya geldiği renkli ve coşkulu etkinliklerdir. Her bölgenin kendine özgü matsuri (festival) geleneği vardır ve yıl boyunca yüzlercesi düzenlenir. Özellikle yaz ayları, festival mevsiminin en yoğun olduğu dönemdir. İnsanlar geleneksel yukata kıyafetlerini giyer, sokaklar renkli fenerlerle süslenir ve havai fişek gösterileri (hanabi taikai) ile gökyüzü aydınlanır.En bilinen festivallerden biri olan Gion Matsuri, Kyoto’da temmuz ayında düzenlenir ve yüzlerce yıllık geçmişe sahiptir. Devasa tahta geçit arabalarıyla yapılan tören yürüyüşleri, festivalin en dikkat çekici anlarından biridir. Tokyo’daki Sanja Matsuri, Asakusa bölgesinde gerçekleşir ve dini taşıyıcıların (mikoshi) kalabalık sokaklarda taşınmasıyla ünlüdür.Kış aylarında ise Sapporo Kar Festivali (Yuki Matsuri), devasa buzdan ve kardan heykellerle turistleri kendine çeker. Ayrıca ilkbaharda Hanami, resmi bir festival olmasa da sakura (kiraz çiçeği) izleme geleneğiyle neredeyse ulusal bir kutlamaya dönüşür.Japon festivalleri, geleneksel müzik, dans, sokak yiyecekleri ve birlikte eğlenmenin ruhunu taşır. Bu festivaller, Japon kültürünün yaşayan birer parçası olarak hem yerel halkı hem de ziyaretçileri büyüler.",
    ulasimTitle: "Ulaşım",
    ulasimText: "Japonya, dünyanın en gelişmiş ve dakik ulaşım sistemlerinden birine sahiptir. Özellikle büyük şehirlerde metro, tren ve otobüs ağı son derece yaygındır ve günlük yaşamın vazgeçilmez bir parçasıdır. Japon trenleri, dakikliğiyle dünyaca ünlüdür; saniyelik gecikmeler bile anons edilerek yolculardan özür dilenir. Şehir içi ulaşımda kullanılan Suica ve Pasmo gibi elektronik kartlar, hem metroda hem otobüste hem de marketlerde geçerlidir.                      Ülkenin simgesi haline gelmiş Shinkansen (hızlı tren), saatte 300 km’ye varan hızıyla şehirler arası ulaşımı hem hızlı hem de konforlu hale getirir. Tokyo’dan Kyoto’ya yaklaşık 2,5 saatte ulaşmak mümkündür. İç hat uçuşları da yaygındır, ancak çoğu insan zaman ve konfor açısından Shinkansen’i tercih eder.                                    Bisiklet de Japonya’da yaygın bir ulaşım aracıdır. Özellikle küçük şehirlerde ve banliyölerde birçok kişi işe ya da okula bisikletle gider. Ayrıca yaya yolları düzenlidir ve yayalara öncelik verilir. Trafik soldan akar ve sürücüler oldukça dikkatli ve kurallara uygundur.                                    Genel olarak Japonya’daki ulaşım sistemi, güvenilirliği, temizliği ve erişilebilirliğiyle dikkat çeker. Ziyaretçiler için de oldukça kullanıcı dostudur; birçok durakta İngilizce bilgilendirme bulunur ve yönlendirme sistemleri oldukça net tasarlanmıştır.",
    egitimTitle: "Eğitim",
    egitimText: "Japonya'da eğitim sistemi, disiplin, sorumluluk ve toplumsal değerlere dayalı güçlü bir yapıya sahiptir. Zorunlu eğitim 6 yıl ilkokul ve 3 yıl ortaokul olmak üzere toplam 9 yıldır. Öğrenciler genellikle üniformalı ve okula yürüyerek ya da toplu taşıma ile giderler. Küçük yaşlardan itibaren temizlik, zaman yönetimi ve grup bilinci gibi değerler kazandırılır. Örneğin Japon okullarında öğrenciler kendi sınıflarını temizler, bu sayede hem sorumluluk hem de toplumsal saygı gelişir.Eğitim yılı nisan ayında başlar ve martta sona erer. Öğrenciler, derslerin yanı sıra kulüp aktivitelerine (bukatsu) da katılır; bu kulüpler spordan sanata, bilimden edebiyata kadar çeşitli alanları kapsar. Japonya’da sınavlar büyük önem taşır; lise ve üniversiteye geçiş için yoğun sınav hazırlığı yapılır. Özellikle üniversite giriş sınavları (センター試験 / Center Shiken), öğrenciler için hayatlarının dönüm noktası olarak görülür.Teknoloji, Japon eğitim sisteminde önemli bir yer tutar. Okullarda akıllı tahtalar, tabletler ve dijital içerikler yaygın olarak kullanılır. Ancak buna rağmen geleneksel öğretmen–öğrenci ilişkisi ve sınıf disiplini korunur. Japonya’daki eğitim, sadece akademik başarıyı değil, aynı zamanda karakter gelişimini de hedefler.Eğitimdeki bu denge, Japon toplumunun çalışkan, düzenli ve saygılı bireylerden oluşmasını sağlayan temel faktörlerden biridir.",
    dogaTitle:"Doğa Ve Manzaralar",
    dogaText:"Japonya, dört mevsimin belirgin yaşandığı, doğal güzelliklerle dolu bir ülkedir. Volkanik dağlar, yemyeşil ormanlar, sakin göller ve kıyı boyunca uzanan çarpıcı manzaralar Japonya’nın coğrafi çeşitliliğini oluşturur. En ikonik doğal sembollerden biri olan Fuji Dağı, sadece dağcılar için değil, sanatçılar ve gezginler için de ilham kaynağıdır. Güneşin doğuşuyla birlikte Fuji’nin etrafını saran sis, doğanın sunduğu en etkileyici sahnelerden biridir.İlkbaharda sakura (kiraz çiçeği) ağaçları, parkları ve nehir kenarlarını pembeye boyar. Bu dönemde insanlar hanami adı verilen geleneksel çiçek izleme etkinlikleri düzenler. Yazın yeşilin bin bir tonunu barındıran dağ yolları, şelaleler ve bambu ormanları doğa yürüyüşleri için idealdir. Sonbaharda ise momiji adı verilen kızaran akçaağaç yaprakları, Japon bahçelerini ve tapınak yollarını adeta tabloya çevirir.Japonya'nın doğayla kurduğu ilişki sadece estetik değil, ruhsaldır da. Tapınaklar genellikle doğayla iç içe konumlandırılmıştır; taş bahçeleri, koi balıklı havuzlar ve orman içi yollar içsel huzuru yansıtır. Kırsal bölgeler, modern şehirlerin gürültüsünden uzaklaşmak isteyenler için sakin bir sığınaktır.Japonya’da doğa, sadece manzara değil; yaşamın, inancın ve kültürün bir parçasıdır.",
    teknolojiTitle:"Teknoloji Ve Modern Hayat",
    teknolojiText:"Japonya, dünyanın teknoloji öncüsü ülkelerinden biridir ve modern yaşamın her alanında bu üstün teknolojiyi deneyimlemek mümkündür. Akıllı şehir uygulamalarından, robot teknolojilerine, yapay zekâ destekli hizmetlerden, yüksek hızlı internet altyapısına kadar birçok yenilik günlük hayatın bir parçasıdır. Örneğin Tokyo’daki tren istasyonları, yüz tanıma sistemleriyle güvenliği sağlar ve temassız ödeme sistemleri hayatı kolaylaştırır.Evlerde ve iş yerlerinde robotlar temizlik, teslimat ve hatta hasta bakımı gibi görevlerde aktif rol alırken, Japonya’nın teknoloji şirketleri yenilikçi elektronik cihazlar ve otomasyon çözümleri geliştirir. Ayrıca Japonlar, çevreci ve enerji verimli teknolojilere büyük önem verir; elektrikli araçlar ve yenilenebilir enerji kaynakları hızla yaygınlaşmaktadır.Modern yaşam tarzı, yoğun çalışma temposu ve teknolojik gelişmelerle şekillenmiştir. Bununla birlikte Japon toplumu, geleneksel değerler ve modernliği dengede tutmaya büyük özen gösterir. Akıllı şehirlerden, gelişmiş sağlık hizmetlerine, dijital eğitimden kültürel etkinliklere kadar her alanda yenilikçi çözümlerle yaşam kalitesi artırılmaktadır.",
    sanatTitle:"Sanat Ve El İşleri",
    sanatText:"Japonya’nın sanatı ve el sanatları, hem estetik hem de felsefi derinlik taşıyan köklü bir geleneğe dayanır. Sadelik, doğayla uyum ve detaylara gösterilen özen, Japon sanatının temel özellikleridir. Geleneksel Japon sanatı; kaligrafi (書道 / shodō), mürekkep resim sanatı (墨絵 / sumi-e), seramik, origami ve ahşap oymacılığı gibi alanlarda yüzyıllardır sürdürülmektedir.Origami, sadece bir kağıt katlama sanatı değil; sabır, dikkat ve zarafetin ifadesidir. Shodō yani kaligrafi ise, fırçayla yazılan karakterlerin sadece yazı değil birer sanat eseri olarak değerlendirilmesini sağlar. Her fırça darbesi, sanatçının ruh halini ve niyetini yansıtır.Kintsugi adı verilen sanat ise kırılan seramiklerin altınla onarılmasıdır. Bu teknik, kusurların güzelliğini vurgular ve Japonların “kusursuzlukta değil, kusurda güzellik arama” felsefesini yansıtır.Japonya'da ahşap baskı sanatı (浮世絵 / ukiyo-e) da oldukça önemlidir. Edo döneminde gelişen bu sanat formu, günlük yaşamdan manzaralara ve ünlü aktörlere kadar pek çok temayı işler. Bugün bile Japon sanatçıların eserleri, geleneksel tekniklerle modern anlatımları birleştiren özel çalışmalar olarak dünyaca tanınmaktadır.Modern Japon sanatı da geleneksel değerlerden beslenir. Anime, manga, dijital sanat ve moda tasarımı gibi çağdaş sanat türleri, geleneksel estetik anlayışıyla harmanlanır. Sanat ve el işi, Japonya’da sadece üretim değil, bir yaşam biçimidir.",

    linkYasam: "Japonya’da Yaşam",
    linkKultur: "Geleneksel Kültür",
    linkFestival: "Festivaller",
    linkUlasim: "Ulaşım",
    linkEgitim: "Eğitim",
    linkDoga:"Doğa Ve Manzaralar",
    linkTeknoloji:"Teknoloji Ve Modern Yaşam",
    linkSanat:"Sanat Ve El İşleri",

     random1:"Ambalaj Gerçekliği",
     random1T:"Japonya’da ürün ambalajları, içeriği birebir yansıtmak zorundadır. Örneğin bir çikolata paketinde görülen görüntü, içindekinin gerçek boyutu ve görünümüyle uyumlu olmalıdır. Tüketiciye “yanıltıcı” görsel sunmak yasa dışıdır.",
     random2:"Çöp Kutusu Neredeyse Yok",
     random2T:"Japonya’da sokakta çöp kutusu bulmak zor olabilir, çünkü insanlar çöplerini evlerine götürüp ayrıştırarak atarlar. Bu uygulama 1995’teki Tokyo metro saldırısından sonra güvenlik gerekçesiyle yaygınlaşmıştır.",
     random3:"Yiyecek Taklit Sanatı (食品サンプル / shokuhin sanpuru)",
     random3T:"Japon restoranlarında gerçek gibi görünen plastik yemek modelleri vardır. Bu yiyecek taklitleri vitrinlerde sergilenir ve menüden ne geleceğini görsel olarak gösterir.",
     random4:"Vending Machine (Jihanki) Cenneti",
     random4T:"Japonya’da her köşe başında otomatlar bulabilirsin. Ülke genelinde 4 milyondan fazla vending machine vardır. Sıcak çorba, dondurma, pil, şemsiye hatta kravat bile satın alabilirsin.",
     random5:"Okul Temizliğini Öğrenciler Yapar",
     random5T:"Japon okullarında temizlik görevlisi yoktur. Öğrenciler her gün sınıfları, koridorları ve tuvaletleri sırayla temizler. Bu, hem disiplin hem sorumluluk eğitiminin bir parçasıdır.",
     random6:"Otobüs Şoförü Grevi – Ama Hizmet Aksamaz",
     random6T:"Japonya’da grev yapan otobüs şoförleri işe gelmeye devam eder ancak yolculardan ücret almaz. Böylece halkı mağdur etmeden, şirketi protesto ederler.",
     random7:"Tuvalet Teknolojisi",
     random7T:"Japonya’daki tuvaletler teknoloji harikasıdır. Isıtmalı klozet, otomatik temizlik, su sesi efekti ve koku giderici gibi özellikler yaygındır. Bazı tuvaletlerde sizi karşılayan selam sesi bile vardır.",
     random8:"Mevsim Takibi Takıntısı",
     random8T:"Japonlar doğadaki mevsim geçişlerine büyük önem verir. Sakuralar açtığında piknik yapılır (hanami), yapraklar kızardığında yürüyüşe çıkılır (momiji-gari), hatta çay paketleri bile mevsimsel olarak değişir.",

    musicTitle: "🎵 Japon Müzikleri",
    musicIntro: "Japon müziğinin renkli dünyasına hoş geldiniz! Anime açılışlarından pop baladlara kadar, Japonya’nın seslerini keşfedin.",
    
    music0Title: "YOASOBI – 夜に駆ける (Yoru ni Kakeru)",
    music0Genre: "Tür: J-Pop",
    music0Desc: "Hikâye temelli sözleri ve dijital sound'u ile Japon gençliği arasında ikonikleşmiştir.",
    
    music1Title: "LiSA – 紅蓮華 (Gurenge)",
    music1Genre: "Tür: Anime / Rock",
    music1Desc: "Demon Slayer animesinin açılış şarkısı olarak dünya çapında ün kazanmıştır.",
    
    music2Title: "Kenshi Yonezu – Lemon",
    music2Genre: "Tür: J-Pop / Ballad",
    music2Desc: "Melankolik sözleri ve sakin melodisiyle Japonya'da uzun süre listelerde zirvede kalmıştır.",
    
    music3Title: "Aimer – Brave Shine",
    music3Genre: "Tür: Anime / Pop Rock",
    music3Desc: "Fate/stay night: Unlimited Blade Works animesinin açılış şarkısı olarak güçlü vokaliyle öne çıkar.",
    
    music4Title: "Hikaru Utada – First Love",
    music4Genre: "Tür: R&B / Pop",
    music4Desc: "1999 yılında çıkan bu şarkı, Japon R&B sahnesinde devrim yaratmış klasiklerdendir.",

    author1_name: "Dazai Osamu",
    author1_bio: "Japon edebiyatının önemli bir yazarı. Karakteristik olarak karanlık ve trajik temalar işler.",
    author1_book: "İnsanlığımı Yitirirken (Ningen Shikkaku)",
    author1_desc: "Yabancılaşma ve kimlik krizini derinlemesine işleyen otobiyografik roman.",

    author2_name: "Akutagawa Ryunosuke",
    author2_bio: "Japon modern edebiyatının kurucularından, kısa hikayeleriyle tanınır.",
    author2_book: "Rashomon ve Diğer Hikayeler",
    author2_desc: "İnsan doğasının karanlık yanlarını ve ahlaki ikilemleri anlatan hikayeler.",

    author3_name: "Natsume Soseki",
    author3_bio: "Modern Japon edebiyatının öncüsü, Japon toplumunun dönüşümünü eserlerinde işler.",
    author3_book: "Kokoro",
    author3_desc: "Aşk, ihanet ve insan ruhunun karmaşıklığını anlatan önemli roman.",

    author4_name: "Nakahara Chuuya",
    author4_bio: "Japon şiirinin öncü isimlerinden, lirik ve duygusal şiirleriyle tanınır.",
    author4_book: "Çığlıklar ve Fısıltılar (Kōshin)",
    author4_desc: "Duygusal derinlik ve etkileyici imgeler içeren şiir koleksiyonu.",

    author5_name: "Kyouka Izumi",
    author5_bio: "Gotik ve fantastik öğelerle özgün eserler veren Japon yazarı.",
    author5_book: "Gecenin Kralı (Yoru no Ou)",
    author5_desc: "Gizemli, atmosferik anlatımla dikkat çeken kısa roman.",

    anime: "🎬 Popüler Animeler",
    animeIntro: "Bu bölümde Japonya'nın öne çıkan animelerini tanıyın:",

    anime0Title: "Your Name (Kimi no Na wa)",
    anime0Desc: "Zamanda ve mekânda birbirine bağlanan iki gencin duygusal hikâyesi.",

    anime1Title: "Spirited Away (Sen to Chihiro no Kamikakushi)",
    anime1Desc: "Bir kızın ruhlar dünyasında yaşadığı büyülü macera.",

    anime2Title: "Attack on Titan (Shingeki no Kyojin)",
    anime2Desc: "İnsanlık ile devler arasında geçen epik bir hayatta kalma savaşı.",

    anime3Title: "86 (Eighty Six)",
    anime3Desc: "Savaşın gerçek yüzünü gösteren distopik bir askeri anime.",

    anime4Title: "Death Note",
    anime4Desc: "Ölüm defteriyle adaleti sağlamaya çalışan bir dahinin karanlık öyküsü.",

    learnTitle:"Japonca Öğren",
    
    mean1: "Günaydın",
    mean2: "Merhaba",
    mean3: "İyi akşamlar",
    mean4: "Hoşça kal",
    mean5: "Görüşürüz",
    mean6: "Tanıştığımıza memnun oldum",
    mean7: "Size emanetim / Lütfen iyi davranın",
    mean8: "Teşekkürler",
    mean9: "Afedersiniz / Pardon",
    mean10: "Özür dilerim",

    mean11: "Ben Ai’yim.",
    mean12: "Japonya’dan geldim.",
    mean13: "Öğrenciyim.",
    mean14: "Japonca çalışıyorum.",
    mean15: "Adın ne?",
    mean16B: "Ben öğrenciyim.",
    mean17B: "O (erkek) öğretmendir.",
    mean18B: "Bu bir kitaptır.",

     mean19: "1",
    mean20: "2",
    mean21: "3",
    mean22: "4",
    mean23: "5",
    mean24: "1 saat",
    mean25: "5 dakika",
    mean26: "10 dakika",
    mean27B: "Şimdi saat 3.",
    mean28B: "Saat 4:05.",

    mean29: "Burası",
    mean30: "Şurası",
    mean31: "Orası",
    mean32: "Neresi",
    mean33: "Tuvalet nerede?",
    mean34: "Dümdüz",
    mean35: "Sağ",
    mean36: "Sol",
    mean37B: "Tuvalet nerede?",
    mean38B: "Dümdüz gidin, sağda.",

      mean39: "Ne kadar",
    mean40: "Bu",
    mean41: "Şu",
    mean42: "O",
    mean43: "Bu (isimle)",
    mean44: "Şu (isimle)",
    mean45: "O (isimle)",
    mean46: "Ucuz",
    mean47: "Pahalı",
    mean48: "Lütfen",
    mean49B: "Bu ne kadar?",
    mean50B: "Bu kitabı lütfen.",

     mean51: "Yemek yemek",
    mean52: "İçmek",
    mean53: "Gitmek",
    mean54: "Gelmek",
    mean55: "Görmek, izlemek",
    mean56: "Yazmak",
    mean57: "Okumak",
    mean58: "Konuşmak",
    mean59B: "Ben yerim.",
    mean60B: "Sen içersin.",

    grammarBoxTitle: "Gramer Notları",
    grammarNote1: "AもBです – “A da B’dir” anlamında kullanılır.",
    grammarNote2: "Aのかみ – “A’nın kağıdı” gibi sahiplik belirtir.",
    grammarNote3: "です – Cümle sonunda nezaket ifadesi.",

    grammarBox2Title: "Gramer Partikülleri",
    particleHa: "は (ha) – Konu belirtir, cümlede anahtar rol oynar.",
    particleHaExample: "わたしは学生です。 (Ben öğrenciyim.)",
    particleWo: "を (wo) – Nesne belirtir, yüklemin nesnesidir.",
    particleWoExample: "りんごを食べます。 (Elma yerim.)",
    particleNi: "に (ni) – Yer ve zaman bildirir, yönelme eki olarak kullanılır.",
    particleNiExample: "学校に行きます。 (Okula giderim.)",

    grammarBox3Title: "Olumlu ve Olumsuz İfadeler",
    exprSuki: "すき (suki) – Sevmek, hoşlanmak.",
    exprSukiExample: "わたしはりんごがすきです。 (Ben elmayı severim.)",
    exprKirai: "きらい (kirai) – Sevmemek, hoşlanmamak.",
    exprKiraiExample: "にくがきらいです。 (Etten hoşlanmam.)",
    exprArimasen: "ありません (arimasen) – Olumsuz varlık eki.",
    exprArimasenExample: "おかねがありません。 (Param yok.)",
    exprArimasu: "あります (arimasu) – Olumlu varlık eki.",
    exprArimasuExample: "いぬがいます。 (Köpek var.)",

    conjunctionBoxTitle: "Bağlaçlar (接続詞)",
    colWord: "Bağlaç",
    colReading: "Okunuş",
    colMeaning: "Anlamı",
    colExample: "Örnek Cümle",
    conj1Word: "と",
    conj1Reading: "to",
    conj1Meaning: "ve, ile",
    conj1Example: "りんごとみかんを食べます。 (Elma ve mandalina yerim.)",
    conj2Word: "しかし",
    conj2Reading: "shikashi",
    conj2Meaning: "ancak, fakat",
    conj2Example: "雨が降っています。しかし、出かけます。 (Yağmur yağıyor, ancak dışarı çıkacağım.)",
    conj3Word: "だから",
    conj3Reading: "dakara",
    conj3Meaning: "bu yüzden, o yüzden",
    conj3Example: "疲れました。だから、休みます。 (Yoruldum. Bu yüzden dinleneceğim.)",
    conj4Word: "それに",
    conj4Reading: "soreni",
    conj4Meaning: "üstelik, ayrıca",
    conj4Example: "宿題をしました。それに、掃除もしました。 (Ödevimi yaptım. Üstelik temizlik de yaptım.)",
    conj5Word: "けれども",
    conj5Reading: "keredomo",
    conj5Meaning: "ama, fakat",
    conj5Example: "行きたいけれども、忙しいです。 (Gitmek istiyorum ama meşgulüm.)",

    linkSelam: "Selamlaşma Ve Temel İfadeler",
    linkTan: "Tanışma Ve Kendini Tanıtma",
    linkSayi: "Sayılar Ve Saatler",
    linkYer: "Yer Ve Yön Bildirme",
    linkAlis: "Alışveriş Ve Fiyat Sorma",
    linkFiil: "Günlük Fiiller",
    linkGramer: "Gramer Notları",
    linkPart: "Gramer Partikülleri",
    linkOlumlu: "Olumlu ve Olumsuz İfadeler",
    linkBag: "Bağlaçlar",

  },

  en: {
    title: "SakuraPages",
    navHome: "Home",
    navJapan: "Japan",
    navLearn: "Japanese",

    homeTitle: "Home",
    homeTitle2: "Are you ready to explore Japan under the cherry blossoms?",
    homeText: "Welcome to Sakura Pages. Sit back, relax, and enjoy learning about Japan and getting a feel for the Japanese language. We’re taking you on a journey to Japan. You can explore cultural and daily life topics in the Japan section, or begin a simple language journey in the Japanese section with everyday expressions. Sakura Pages is here to support you in both. So, shall we begin?",


    japanTitle: "Japan",
    japanText: "Japan is an island country located in East Asia, surrounded by the Pacific Ocean. It consists of four major islands—Honshu, Hokkaido, Kyushu, and Shikoku—as well as thousands of smaller ones. The capital is Tokyo, and with a population of around 125 million, Japan is one of the most populous countries in the world. The official language is Japanese, which uses three writing systems: hiragana, katakana, and kanji. Japan is governed as a constitutional monarchy, with the Emperor serving as a cultural symbol.Japan beautifully blends traditional and modern lifestyles. From ancient temples to advanced technology, and from tea ceremonies to anime and manga, the country offers a wide range of cultural experiences. It is a global leader in industries like automotive, electronics, gaming, and robotics.Japan’s natural beauty is also remarkable. The country is known for its active volcanoes, frequent earthquakes, and distinct four seasons. Mount Fuji has become a national symbol. From snowy Hokkaido in the north to the tropical islands of Okinawa in the south, Japan offers a wide variety of landscapes.Japanese cuisine is world-renowned. Dishes like sushi, ramen, tempura, and matcha are loved by both locals and tourists. With its clean cities, safe streets, and respectful culture, Japan offers a unique and enriching lifestyle worth exploring.",
    yasamTitle: "Life in Japan",
    yasamText:"Japan is a unique country that balances the speed of modern life with traditional values. Life in the cities is quite intense and systematic; in major cities like Tokyo, Osaka, and Kyoto, things move fast. Public transportation is known for its punctuality, and people generally adopt a disciplined, respectful lifestyle that values social rules. Not talking on the phone while walking and being quiet in public transport are part of daily life.Homes are generally compact and functional; small apartments are common in city centers. Life in Japan can be expensive, but it offers a high standard of living in areas such as healthcare, safety, cleanliness, and access to technology. Each part of Japan reflects a unique beauty through the distinct four seasons. Streets covered in cherry blossoms in spring and parks filled with red leaves in autumn are part of everyday life.The Japanese place great importance on politeness and harmony in social life. In work environments, hierarchy and group harmony are emphasized, while in friendships, mutual understanding and personal space are respected. Also, Japan has one of the highest life expectancies in the world, influenced by healthy eating habits and an active lifestyle.",
    kulturTitle: "Traditional Culture",
    kulturText: "Japanese culture is known for its elegance and simplicity, expressed through many traditional elements. One of these is the kimono, a traditional garment worn both in daily life and on special occasions. The color, pattern, and fabric of the kimono carry different meanings; for example, white and gold tones are preferred at weddings, while vibrant summer versions called yukata are worn at festivals.Another important cultural tradition is the tea ceremony (茶道 / sadō), which represents a philosophy beyond simply drinking tea. The host prepares and serves matcha (powdered green tea) to the guest with calm and deliberate movements. The ritual highlights values such as simplicity, respect, harmony, and tranquility.Ikebana (生け花), the art of flower arrangement, is different from Western floral designs. It aims to reflect the spirit of nature and the changing seasons. The direction of branches, the use of empty space, and color balance all contribute to a composition that becomes a form of meditation.These three traditional arts reflect Japan’s deep respect for nature, aesthetics, and inner harmony. Even in modern Japan, they are still honored and continue to carry the grace of the past into the present.",
    festivalTitle: "Festivals",
    festivalText: "Festivals in Japan, known as matsuri, are vibrant celebrations that reflect both religious traditions and seasonal transitions. Each region has its own unique festivals, and hundreds are held throughout the year. Summer is the peak festival season, when people wear traditional yukata, streets are decorated with colorful lanterns, and fireworks shows (hanabi taikai) light up the night sky.One of the most famous festivals is Gion Matsuri in Kyoto, held every July, with a history dating back centuries. The massive wooden parade floats are the highlight of the event. In Tokyo, Sanja Matsuri, held in Asakusa, is famous for the lively carrying of portable shrines (mikoshi) through crowded streets.During winter, the Sapporo Snow Festival (Yuki Matsuri) attracts visitors with its massive ice and snow sculptures. In spring, while not an official festival, Hanami—the tradition of cherry blossom viewing—becomes a nationwide celebration.Japanese festivals are full of traditional music, dance, street food, and a sense of community joy. They remain a living part of Japanese culture, enchanting both locals and visitors alike.",
    ulasimTitle: "Transportation",
    ulasimText: "Japan has one of the most advanced and punctual transportation systems in the world. In major cities, the networks of subways, trains, and buses are widespread and an essential part of daily life. Japanese trains are world-famous for their punctuality—delays of even a few seconds are announced with apologies. Electronic cards like Suica and Pasmo are commonly used for transportation and can also be used for shopping in convenience stores.                        The iconic Shinkansen (bullet train) makes intercity travel both fast and comfortable, reaching speeds of up to 300 km/h. For example, it takes about 2.5 hours to travel from Tokyo to Kyoto. While domestic flights are also available, many people prefer the Shinkansen for its convenience.                               Bicycles are another common mode of transport in Japan. In smaller cities and suburban areas, many people commute to work or school by bike. Sidewalks are well-organized, and pedestrians are given priority. Traffic flows on the left side, and drivers tend to be very careful and respectful of traffic rules.                           Overall, Japan’s transportation system is known for its reliability, cleanliness, and accessibility. It’s also tourist-friendly, with English signage and clear navigation available at many stations.",
    egitimTitle: "Education",
    egitimText: "Japan’s education system is built on strong values such as discipline, responsibility, and social harmony. Compulsory education includes 6 years of elementary school and 3 years of junior high school, totaling 9 years. Students usually wear uniforms and walk or take public transportation to school. From a young age, they learn values like cleanliness, time management, and teamwork. For example, in many schools, students clean their own classrooms, fostering a sense of responsibility and mutual respect.The academic year begins in April and ends in March. In addition to regular classes, students participate in club activities (bukatsu), which range from sports and arts to science and literature. Exams play a significant role in Japanese education; students prepare rigorously for high school and university entrance exams. The university entrance exam (Center Shiken) is often considered a major turning point in a student’s life.Technology also plays a key role in Japanese education. Smart boards, tablets, and digital learning materials are widely used, yet the traditional teacher-student relationship and classroom discipline are still maintained. Education in Japan aims not only for academic success but also for character development.This balance is one of the core reasons why Japanese society is known for its hardworking, orderly, and respectful individuals.",
    dogaTitle:"Nature and Landscapes",
    dogaText:"Japan is a country where all four seasons are clearly experienced and filled with natural beauty. Volcanic mountains, lush forests, peaceful lakes, and stunning coastal views reflect Japan’s diverse geography. One of the most iconic natural symbols is Mount Fuji, which inspires not only climbers but also artists and travelers. The sight of morning mist surrounding Fuji is one of nature’s most breathtaking scenes.In spring, sakura (cherry blossoms) paint parks and riversides in shades of pink. During this time, people gather for traditional flower-viewing events called hanami. In summer, mountain trails, waterfalls, and bamboo forests filled with shades of green offer ideal paths for hiking. In autumn, momiji, the red maple leaves, turn gardens and temple paths into living paintings.Japan’s connection with nature is not only aesthetic but also spiritual. Temples are often built in harmony with their surroundings—stone gardens, koi ponds, and forested paths reflect a sense of inner peace. The countryside offers a calm retreat for those wishing to escape the noise of modern cities.In Japan, nature is not just scenery; it is part of life, belief, and culture.",
    teknolojiTitle:"Technology and Modern Life",
    teknolojiText:"Japan is one of the world’s leading countries in technology, and this advanced technology is experienced in every aspect of modern life. From smart city applications and robotics to AI-powered services and high-speed internet infrastructure, many innovations are part of daily life. For example, train stations in Tokyo use facial recognition systems for security, and contactless payment methods make life easier.Robots actively assist with cleaning, deliveries, and even patient care in homes and workplaces, while Japanese technology companies develop innovative electronic devices and automation solutions. Additionally, the Japanese place great importance on eco-friendly and energy-efficient technologies; electric vehicles and renewable energy sources are spreading rapidly.The modern lifestyle is shaped by a fast-paced work culture and technological advancements. However, Japanese society carefully balances traditional values with modernity. From smart cities and advanced healthcare to digital education and cultural events, innovative solutions enhance the quality of life in many areas.",
    sanatTitle:"Arts and Crafts",
    sanatText:"Japanese art and handcrafts are rooted in a long-standing tradition that reflects both aesthetic and philosophical depth. Simplicity, harmony with nature, and attention to detail are key characteristics of Japanese art. Traditional forms include calligraphy (shodō), ink painting (sumi-e), ceramics, origami, and wood carving, all of which have been practiced for centuries.Origami is more than just paper folding—it represents patience, precision, and elegance. Shodō, or calligraphy, turns written characters into works of art, with each brushstroke reflecting the artist's emotion and intention.A unique Japanese art form, kintsugi, involves repairing broken ceramics with gold. It symbolizes the beauty in imperfection and embodies the idea that flaws are not something to hide, but to highlight.The traditional woodblock printing art (ukiyo-e) also holds an important place in Japanese history. Originating during the Edo period, it features scenes from daily life, nature, and famous actors. Even today, many Japanese artists blend traditional techniques with modern expression.Modern Japanese art draws inspiration from these traditional values. Anime, manga, digital art, and fashion design are contemporary forms that still carry the spirit of Japanese aesthetics. In Japan, art and handcrafts are not just creative activities—they are a way of life.",

     linkYasam: "Life in Japan",
     linkKultur: "Traditional Culture",
     linkFestival: "Festivals",
     linkUlasim: "Transportation",
     linkEgitim: "Education",
     linkDoga:"Nature and Landscapes",
     linkTeknoloji:"Technology and Modern Life",
     linkSanat:"Arts and Crafts",

     random1:"Packaging Accuracy",
     random1T:"In Japan, product packaging must accurately represent what’s inside. For example, if a snack shows a certain size or look on the package, the actual item must match it. Misleading visuals are not allowed.",
     random2:"Almost No Trash Bins",
     random2T:"It’s hard to find trash cans in public spaces in Japan. People usually take their garbage home and sort it. This became common after the 1995 Tokyo subway attack for security reasons.",
     random3:"Fake Food Art (Shokuhin Sanpuru)",
     random3T:"Many restaurants in Japan display realistic plastic food models in their windows. These help customers visually understand what they’ll be served.",
     random4:"Vending Machine Paradise",
     random4T:"Japan has over 4 million vending machines across the country. You can buy hot soup, ice cream, batteries, umbrellas, or even neckties from them.",
     random5:"Students Clean the School",
     random5T:"In Japanese schools, students clean classrooms, hallways, and even toilets themselves. This practice teaches discipline, teamwork, and responsibility.",
     random6:"Bus Driver Strikes Still Offer Service",
     random6T:"When Japanese bus drivers go on strike, they continue to work—but they stop collecting fares. This way, the public isn’t affected, but the company is pressured.",
     random7:"High-Tech Toilets",
     random7T:"Japanese toilets are often equipped with seat warmers, bidet functions, sound effects, and deodorizing systems. Some even greet users with a welcoming voice.",
     random8:"Seasonal Awareness",
     random8T:"Japanese people pay great attention to seasonal changes. In spring, people hold flower-viewing parties (hanami), and in autumn they enjoy red leaves (momiji-gari). Even tea packaging changes with the seasons.",


    musicTitle: "🎵 Japanese Music",
    musicIntro: "Welcome to the colorful world of Japanese music! Discover Japan’s sounds from anime openings to pop ballads.",
    
    music0Title: "YOASOBI – 夜に駆ける (Yoru ni Kakeru)",
    music0Genre: "Genre: J-Pop",
    music0Desc: "Known for its story-driven lyrics and digital sound, it became iconic among Japanese youth.",
    
    music1Title: "LiSA – 紅蓮華 (Gurenge)",
    music1Genre: "Genre: Anime / Rock",
    music1Desc: "Famous worldwide as the opening song for the anime Demon Slayer.",
    
    music2Title: "Kenshi Yonezu – Lemon",
    music2Genre: "Genre: J-Pop / Ballad",
    music2Desc: "With melancholic lyrics and a calm melody, it topped the charts in Japan for a long time.",
    
    music3Title: "Aimer – Brave Shine",
    music3Genre: "Genre: Anime / Pop Rock",
    music3Desc: "Known for its powerful vocals as the opening song of Fate/stay night: Unlimited Blade Works.",
    
    music4Title: "Hikaru Utada – First Love",
    music4Genre: "Genre: R&B / Pop",
    music4Desc: "Released in 1999, this song is a classic that revolutionized the Japanese R&B scene.",

    author1_name: "Dazai Osamu",
    author1_bio: "An important Japanese writer known for dark and tragic themes.",
    author1_book: "No Longer Human (Ningen Shikkaku)",
    author1_desc: "An autobiographical novel delving into alienation and identity crisis.",

    author2_name: "Akutagawa Ryunosuke",
    author2_bio: "One of the founders of modern Japanese literature, famous for short stories.",
    author2_book: "Rashomon and Other Stories",
    author2_desc: "Stories depicting the dark sides of human nature and moral dilemmas.",

    author3_name: "Natsume Soseki",
    author3_bio: "A pioneer of modern Japanese literature who portrayed social changes.",
    author3_book: "Kokoro",
    author3_desc: "A significant novel about love, betrayal, and the complexity of the human spirit.",

    author4_name: "Nakahara Chuuya",
    author4_bio: "A leading Japanese poet known for lyrical and emotional poetry.",
    author4_book: "Screams and Whispers (Kōshin)",
    author4_desc: "A poetry collection full of emotional depth and vivid imagery.",

    author5_name: "Kyouka Izumi",
    author5_bio: "A Japanese writer known for gothic and fantastic elements.",
    author5_book: "The King of the Night (Yoru no Ou)",
    author5_desc: "A mysterious short novel with atmospheric narration.",

    anime: "🎬 Popular Anime",
    animeIntro: "Discover Japan’s standout anime titles in this section:",

    anime0Title: "Your Name (Kimi no Na wa)",
    anime0Desc: "An emotional story of two teens connected across time and space.",

    anime1Title: "Spirited Away (Sen to Chihiro no Kamikakushi)",
    anime1Desc: "A girl’s magical adventure in the world of spirits.",

    anime2Title: "Attack on Titan (Shingeki no Kyojin)",
    anime2Desc: "A survival war between humans and titans.",

    anime3Title: "86 (Eighty Six)",
    anime3Desc: "A dystopian military anime revealing the brutal truth of war.",

    anime4Title: "Death Note",
    anime4Desc: "A genius uses a deadly notebook to deliver his own justice.",


    learnTitle:" Learn Japanese",

    mean1: "Good morning",
    mean2: "Hello",
    mean3: "Good evening",
    mean4: "Goodbye",
    mean5: "See you",
    mean6: "Nice to meet you",
    mean7: "Please take care of me",
    mean8: "Thank you",
    mean9: "Excuse me / Sorry",
    mean10: "I'm sorry",

    mean11: "I'm Ai.",
    mean12: "I came from Japan.",
    mean13: "I'm a student.",
    mean14: "I'm studying Japanese.",
    mean15: "What's your name?",
    mean16B: "I'm a student.",
    mean17B: "He is a teacher.",
    mean18B: "This is a book.",

    mean19: "1",
    mean20: "2",
    mean21: "3",
    mean22: "4",
    mean23: "5",
    mean24: "1 o'clock",
    mean25: "5 minutes",
    mean26: "10 minutes",
    mean27B: "It's 3 o'clock now.",
    mean28B: "It's 4:05.",

     mean29: "Here",
    mean30: "There (near you)",
    mean31: "Over there (far away)",
    mean32: "Where",
    mean33: "Where is the toilet?",
    mean34: "Straight ahead",
    mean35: "Right",
    mean36: "Left",
    mean37B: "Where is the toilet?",
    mean38B: "Go straight, it's on the right.",

     mean39: "How much",
    mean40: "This",
    mean41: "That (near you)",
    mean42: "That (over there)",
    mean43: "This (with noun)",
    mean44: "That (with noun)",
    mean45: "That over there (with noun)",
    mean46: "Cheap",
    mean47: "Expensive",
    mean48: "Please",
    mean49B: "How much is this?",
    mean50B: "This book, please.",

     mean51: "To eat",
    mean52: "To drink",
    mean53: "To go",
    mean54: "To come",
    mean55: "To see, to watch",
    mean56: "To write",
    mean57: "To read",
    mean58: "To speak",
    mean59B: "I eat.",
    mean60B: "You drink.",

     grammarBoxTitle: "Grammar Notes",
    grammarNote1: "AもBです – Used to say “A is also B”.",
    grammarNote2: "Aのかみ – Indicates possession, like “A’s paper”.",
    grammarNote3: "です – Politeness marker at sentence end.",

    grammarBox2Title: "Grammar Particles",
    particleHa: "は (ha) – Indicates the topic; key role in sentence.",
    particleHaExample: "わたしは学生です。 (I am a student.)",
    particleWo: "を (wo) – Marks the object of the verb.",
    particleWoExample: "りんごを食べます。 (I eat an apple.)",
    particleNi: "に (ni) – Indicates place/time, marks direction.",
    particleNiExample: "学校に行きます。 (I go to school.)",

    grammarBox3Title: "Positive and Negative Expressions",
    exprSuki: "すき (suki) – To like, to be fond of.",
    exprSukiExample: "わたしはりんごがすきです。 (I like apples.)",
    exprKirai: "きらい (kirai) – To dislike.",
    exprKiraiExample: "にくがきらいです。 (I dislike meat.)",
    exprArimasen: "ありません (arimasen) – Negative existence verb.",
    exprArimasenExample: "おかねがありません。 (I have no money.)",
    exprArimasu: "あります (arimasu) – Positive existence verb.",
    exprArimasuExample: "いぬがいます。 (There is a dog.)",

    conjunctionBoxTitle: "Conjunctions (接続詞)",
    colWord: "Conjunction",
    colReading: "Reading",
    colMeaning: "Meaning",
    colExample: "Example Sentence",
    conj1Word: "と",
    conj1Reading: "to",
    conj1Meaning: "and, with",
    conj1Example: "りんごとみかんを食べます。 (I eat apples and mandarins.)",
    conj2Word: "しかし",
    conj2Reading: "shikashi",
    conj2Meaning: "but, however",
    conj2Example: "雨が降っています。しかし、出かけます。 (It's raining. However, I will go out.)",
    conj3Word: "だから",
    conj3Reading: "dakara",
    conj3Meaning: "so, therefore",
    conj3Example: "疲れました。だから、休みます。 (I’m tired. Therefore, I will rest.)",
    conj4Word: "それに",
    conj4Reading: "soreni",
    conj4Meaning: "moreover, also",
    conj4Example: "宿題をしました。それに、掃除もしました。 (I did homework. Moreover, I cleaned too.)",
    conj5Word: "けれども",
    conj5Reading: "keredomo",
    conj5Meaning: "but, although",
    conj5Example: "行きたいけれども、忙しいです。 (I want to go, but I’m busy.)",

    linkSelam: "Greetings and Basic Phrases",
    linkTan: "Introducing Yourself",
    linkSayi: "Numbers and Time",
    linkYer: "Location and Directions",
    linkAlis: "Shopping and Asking Prices",
    linkFiil: "Daily Verbs",
    linkGramer: "Grammar Notes",
    linkPart: "Grammar Particles",
    linkOlumlu: "Positive and Negative Phrases",
    linkBag: "Conjunctions",

  },

  jp: {
    title: "SakuraPages",
    navHome: "ホーム",
    navJapan: "日本",
    navLearn: "日本語",

    homeTitle: "ホーム",
    homeTitle2: "桜の木陰で日本を探検する準備はできていますか？",
    homeText: "Sakura Pagesへようこそ。リラックスして、日本について学び、日本語に触れる旅を楽しんでください。私たちはあなたを日本への旅にご案内します。日本セクションでは日本の文化や生活を学び、日本語セクションでは日常会話を通して言語の旅を始めることができます。Sakura Pagesはどちらの面でもあなたをサポートします。では、始めましょうか？",

   
     japanTitle: "日本",
    japanText: "日本は東アジアに位置し、太平洋に囲まれた島国です。本州、北海道、九州、四国の4つの主要な島と、数千の小さな島々から成り立っています。首都は東京で、人口は約1億2500万人と、世界でも有数の人口を誇ります。公用語は日本語で、ひらがな、カタカナ、漢字の3つの文字体系が使われています。日本は立憲君主制の国家であり、天皇は文化的な象徴としての役割を担っています。日本は、伝統と現代の生活が美しく融合した国です。古代の寺院から最先端の技術、茶道からアニメやマンガに至るまで、幅広い文化体験を提供しています。自動車、電子機器、ゲーム、ロボット産業においても世界のリーダーです。また、日本の自然の美しさも際立っています。活火山や地震が多く、四季の変化がはっきりとしています。富士山は日本を象徴する存在です。北の北海道の雪景色から南の沖縄の熱帯の風景まで、多様な自然の魅力を楽しむことができます。日本の料理は世界的に知られており、寿司、ラーメン、天ぷら、抹茶などは地元の人々にも観光客にも愛されています。清潔な都市、安全な街、礼儀正しい文化の中で、日本は訪れる価値のある特別な体験を提供する国です。",
    yasamTitle: "日本での生活",
    yasamText:"日本は、現代生活のスピードと伝統的な価値観をバランスよく両立させているユニークな国です。都市部の生活は非常に忙しく、体系的です。特に東京、大阪、京都のような大都市では、日常の流れが速く進みます。公共交通機関は時間の正確さで有名で、人々は一般的に規律正しく、礼儀正しく、社会的ルールを重視する生活スタイルを採用しています。歩きながら電話をしない、電車の中では静かにするなどのルールは日常生活の一部です。住宅は一般的にコンパクトで機能的です。都市中心部では小さなアパートが一般的です。日本での生活費は高い場合もありますが、医療、安全、清潔さ、テクノロジーへのアクセスなど、多くの面で高水準の生活を提供しています。日本の各地では四季の変化がはっきりしており、それぞれが独特の美しさを持っています。春には桜で埋め尽くされた街並み、秋には紅葉で彩られた公園などが、日常の一部となっています。日本人は社会生活において礼儀や調和を非常に大切にします。職場では上下関係や集団の調和が重視され、友人関係ではお互いの理解と距離感が保たれます。また、日本は世界でも有数の長寿国であり、健康的な食習慣や活動的なライフスタイルがその理由の一つです。",
    kulturTitle: "伝統文化",
    kulturText: "日本文化は、優雅さと簡素さが際立つ多くの伝統的な要素によって表現されています。そのひとつが着物であり、日常生活だけでなく特別な場面でも着用される伝統的な衣装です。着物の色や柄、生地にはそれぞれ意味があり、結婚式では白や金の色が、夏祭りではカラフルな夏用の浴衣が選ばれます。もう一つの重要な伝統は、**茶道（さどう）**です。これは単なるお茶を飲む行為ではなく、深い哲学を表すものです。主人は、静かで丁寧な動作で抹茶を用意し、客に提供します。この儀式では、簡素さ、敬意、調和、そして心の静けさといった価値が重視されます。**生け花（いけばな）**は、花を生ける芸術であり、西洋のフラワーアレンジメントとは異なります。自然の精神や季節の移ろいを表現することが目的であり、枝の向き、空間の使い方、色のバランスなどを通して、まるで瞑想のような作品が生み出されます。これら三つの伝統芸術は、日本が自然、美意識、そして内面の調和をいかに大切にしているかを反映しています。現代の日本でもこれらは尊重され、過去の優雅さを今に伝え続けています。",
    festivalTitle: "お祭り",
    festivalText: "日本の祭り（祭り / まつり）は、宗教的な伝統や季節の移り変わりを祝う華やかな行事です。各地域には独自の祭りがあり、年間を通して数百もの祭りが開催されます。特に夏は祭りの最盛期であり、人々は伝統的な浴衣を着て、通りは色とりどりの提灯で飾られ、花火大会（花火大会 / はなびたいかい）で夜空が彩られます。最も有名な祭りの一つが、京都で7月に行われる**祇園祭（ぎおんまつり）です。巨大な木製の山鉾（やまほこ）が通りを練り歩く様子は、祭りの見どころの一つです。東京の浅草で開催される三社祭（さんじゃまつり）**では、神輿（みこし）を担いで賑やかに練り歩く様子が見られます。冬には、**札幌雪まつり（ゆきまつり）が氷や雪で作られた巨大な彫刻で観光客を魅了します。春には公式な祭りではありませんが、桜を見る伝統である花見（はなみ）**が全国的なイベントのように祝われます。日本の祭りは、伝統音楽、踊り、屋台の食べ物、そして人々の一体感に満ちています。これらの祭りは、日本文化の生きた一部として、今もなお多くの人々を魅了し続けています。",
    ulasimTitle: "交通",
    ulasimText: "日本は、世界でも最も高度で時間に正確な交通システムを持つ国の一つです。大都市では地下鉄や電車、バスのネットワークが広く整備されており、日常生活に欠かせない存在です。日本の電車は時間の正確さで世界的に有名で、わずかな遅れでもアナウンスと共に謝罪されます。SuicaやPasmoなどのICカードは、交通機関だけでなくコンビニなどの買い物でも使用できます。                                  象徴的な存在である**新幹線（しんかんせん）**は、時速300kmにも達する高速列車で、都市間の移動を迅速かつ快適にしてくれます。例えば、東京から京都までは約2時間半で到着します。国内線の飛行機もありますが、多くの人が利便性の高さから新幹線を選びます。                                               自転車も日本では一般的な移動手段です。特に地方都市や郊外では、多くの人が通勤や通学に自転車を利用しています。歩道は整備されており、歩行者が優先されます。交通は左側通行で、ドライバーは非常に注意深く、交通ルールを守ります。                                    全体として、日本の交通システムは信頼性、清潔さ、そして使いやすさで高く評価されています。観光客にも親切で、多くの駅に英語表記があり、案内表示も分かりやすく設計されています。",
    egitimTitle: "教育",
    egitimText: "日本の教育システムは、規律、責任、そして社会的調和といった価値観に基づいています。義務教育は小学校6年間と中学校3年間、合わせて9年間です。生徒たちは通常、制服を着て、徒歩または公共交通機関で通学します。幼いころから、清掃、時間管理、協調性などの価値が身につけられます。たとえば、多くの学校では生徒が自分たちの教室を掃除し、責任感と相互の敬意を育てます。学年は4月に始まり、翌年の3月に終了します。授業に加えて、生徒は部活動（部活 / ぶかつ）にも参加します。これらの活動はスポーツや芸術、科学、文学など幅広い分野にわたります。日本の教育では試験が非常に重要であり、高校や大学への進学のために生徒たちは熱心に勉強します。特に大学入試（センター試験）は、人生の大きな転機と見なされます。また、日本の教育ではテクノロジーも重要な役割を果たしています。スマートボード、タブレット、デジタル教材などが広く使用されていますが、伝統的な教師と生徒の関係や教室内の規律は今も大切にされています。日本の教育は、学力だけでなく人間性の成長も目指しています。このバランスこそが、日本社会が勤勉で秩序正しく、礼儀正しい人々によって成り立っている理由のひとつです。",
    dogaTitle:"自然と風景",
    dogaText:"日本は四季がはっきりしており、美しい自然に恵まれた国です。火山の山々、青々とした森、静かな湖、そして海岸線に広がる見事な風景は、日本の多様な地形を象徴しています。中でも最も象徴的な自然のシンボルの一つが**富士山（ふじさん）**です。登山者だけでなく、芸術家や旅行者にも大きなインスピレーションを与えています。朝霧に包まれた富士の姿は、自然が見せる最も美しい光景のひとつです。春には**桜（さくら）が公園や川沿いをピンクに染め、伝統的な花見（はなみ）が各地で行われます。夏には緑豊かな山道、滝、竹林がハイキングに最適な場所となります。秋になると紅葉（もみじ）**が色づき、庭園や神社の参道をまるで絵画のように彩ります。日本人にとって自然とのつながりは、見た目の美しさだけでなく、精神的な意味も持ちます。寺院は自然と調和する場所に建てられることが多く、石庭や鯉の池、森の中の小道は心の静けさを映し出します。田舎の地域は、都会の喧騒から離れたい人々にとって静かな避難所となります。日本では、自然はただの風景ではなく、生活、信仰、文化の一部なのです。",
    teknolojiTitle:"テクノロジーと現代生活",
    teknolojiText:"日本は世界有数の技術先進国であり、この高度な技術は現代生活のあらゆる面で体験できます。スマートシティの応用やロボット技術、AIを活用したサービス、高速インターネットのインフラなど、多くの革新が日常生活の一部となっています。例えば、東京の駅では顔認証システムがセキュリティに使われ、非接触決済が生活を便利にしています。家庭や職場では、ロボットが掃除、配達、さらには患者のケアまで積極的に支援し、日本の技術企業は革新的な電子機器や自動化ソリューションを開発しています。さらに、日本人は環境に優しい省エネルギー技術を重視しており、電気自動車や再生可能エネルギーの普及が急速に進んでいます。現代の生活様式は、忙しい労働文化と技術の進歩によって形作られています。しかし、日本社会は伝統的な価値観と現代性のバランスを慎重に保っています。スマートシティや高度な医療、デジタル教育、文化イベントに至るまで、多くの分野で革新的なソリューションが生活の質を向上させています。",
    sanatTitle:"美術と工芸",
    sanatText:"",
    
     linkYasam: "日本での生活",
     linkKultur: "伝統文化",
     linkFestival: "お祭り",
     linkUlasim: "交通",
     linkEgitim: "教育",
     linkDoga:"自然と風景",
     linkTeknoloji:"テクノロジーと現代生活",
     linkArt:"美術と工芸",

    random1:"パッケージの正確さ",
     random1T:"日本では、商品のパッケージは中身と一致していなければなりません。例えば、お菓子のパッケージに描かれたサイズや形は、実際の商品と同じである必要があります。誇張表現は禁止されています。",
     random2:"公共のごみ箱がほとんどない",
     random2T:"日本の街中ではごみ箱を見つけるのが難しいです。多くの人はごみを家に持ち帰って分別して捨てます。これは1995年の地下鉄サリン事件以降、安全上の理由から広まりました。",
     random3:"食品サンプル",
     random3T:"多くのレストランでは、ウィンドウにリアルなプラスチック製の食品サンプルが飾られています。これにより、お客さんは料理のイメージを事前に確認できます。",
     random4:"自動販売機天国",
     random4T:"日本には全国で400万台以上の自動販売機があります。温かいスープ、アイスクリーム、電池、傘、ネクタイまで購入できます。",
     random5:"学校の掃除は生徒がする",
     random5T:"日本の学校では、清掃員を雇わずに生徒たちが毎日教室、廊下、トイレを交代で掃除します。これは、責任感と協力を育む教育の一環です。",
     random6:"バス運転手のストライキでも運行は続く",
     random6T:"日本でバス運転手がストライキをするとき、通常通り運転はしますが、乗客から運賃を取りません。これにより市民に迷惑をかけず、会社にプレッシャーをかけます。",
     random7:"ハイテクトイレ",
     random7T:"日本のトイレは技術的に非常に進んでいます。便座の暖房、ビデ機能、音の演出、消臭機能などが標準で搭載されています。中には「いらっしゃいませ」と挨拶するトイレもあります。",
     random8:"季節感へのこだわり",
     random8T:"日本人は季節の移り変わりに敏感です。春には「花見」で桜を楽しみ、秋には「紅葉狩り」で赤く色づいた葉を鑑賞します。お茶のパッケージまでも季節によって変わることがあります。",

    author1_name: "太宰治",
    author1_bio: "暗く悲劇的なテーマで知られる日本文学の重要な作家。",
    author1_book: "人間失格 (Ningen Shikkaku)",
    author1_desc: "疎外とアイデンティティの危機を深く掘り下げた自伝的小説。",

    author2_name: "芥川龍之介",
    author2_bio: "近代日本文学の創始者の一人で、短編小説で有名。",
    author2_book: "羅生門とその他の物語",
    author2_desc: "人間の暗い側面や道徳的ジレンマを描いた物語。",

    author3_name: "夏目漱石",
    author3_bio: "社会の変化を描いた近代日本文学の先駆者。",
    author3_book: "こころ",
    author3_desc: "愛、裏切り、人間の複雑さを描いた重要な小説。",

    author4_name: "中原中也",
    author4_bio: "叙情的で感情豊かな詩で知られる日本の著名な詩人。",
    author4_book: "叫びと囁き (Kōshin)",
    author4_desc: "感情の深さと鮮やかなイメージに満ちた詩集。",

    author5_name: "泉鏡花",
    author5_bio: "ゴシックや幻想的な要素で知られる日本の作家。",
    author5_book: "夜の王 (Yoru no Ou)",
    author5_desc: "神秘的で雰囲気のある短編小説。",

    anime: "🎬 人気アニメ",
    animeIntro: "このセクションでは日本の注目アニメを紹介します。",

    anime0Title: "君の名は (Your Name)",
    anime0Desc: "時空を超えて繋がる二人の感動的な物語。",

    anime1Title: "千と千尋の神隠し (Spirited Away)",
    anime1Desc: "少女が霊の世界で繰り広げる魔法の冒険。",

    anime2Title: "進撃の巨人 (Attack on Titan)",
    anime2Desc: "人類と巨人との壮絶なサバイバル戦争。",

    anime3Title: "86-エイティシックス-",
    anime3Desc: "戦争の真実を描いたディストピア系ミリタリーアニメ。",

    anime4Title: "デスノート (Death Note)",
    anime4Desc: "死のノートで正義を貫こうとする天才のダークストーリー。",

    musicTitle: "🎵 日本の音楽",
    musicIntro: "日本の音楽の多彩な世界へようこそ！アニメのオープニングからポップバラードまで、日本の音を発見してください。",
    
    music0Title: "YOASOBI – 夜に駆ける (Yoru ni Kakeru)",
    music0Genre: "ジャンル：J-POP",
    music0Desc: "物語性のある歌詞とデジタルサウンドで、日本の若者の間で象徴的な存在となりました。",
    
    music1Title: "LiSA – 紅蓮華 (Gurenge)",
    music1Genre: "ジャンル：アニメ / ロック",
    music1Desc: "アニメ『鬼滅の刃』のオープニング曲として世界的に有名です。",
    
    music2Title: "米津玄師 – Lemon",
    music2Genre: "ジャンル：J-POP / バラード",
    music2Desc: "メランコリックな歌詞と落ち着いたメロディーで、日本で長期間チャートのトップに立ちました。",
    
    music3Title: "Aimer – Brave Shine",
    music3Genre: "ジャンル：アニメ / ポップロック",
    music3Desc: "『Fate/stay night: Unlimited Blade Works』のオープニング曲として力強いボーカルが特徴です。",
    
    music4Title: "宇多田ヒカル – First Love",
    music4Genre: "ジャンル：R&B / ポップ",
    music4Desc: "1999年にリリースされ、日本のR&Bシーンに革命をもたらしたクラシック曲です。",

    learnTitle:"日本語",

     mean1: "朝のあいさつ",
    mean2: "あいさつの基本",
    mean3: "夜のあいさつ",
    mean4: "別れの言葉",
    mean5: "カジュアルな別れの言葉",
    mean6: "初対面の挨拶",
    mean7: "よろしくお願いしますの意味",
    mean8: "感謝の言葉",
    mean9: "軽い謝罪や呼びかけ",
    mean10: "正式な謝罪",
    
      mean11: "自己紹介（じこしょうかい）です。",
    mean12: "出身地（しゅっしんち）を言います。",
    mean13: "職業（しょくぎょう）を言います。",
    mean14: "勉強していることを言います。",
    mean15: "名前をたずねます。",
    mean16B: "A は B です の例文。",
    mean17B: "A は B です の例文。",
    mean18B: "A は B です の例文。",

     mean19: "いち",
    mean20: "に",
    mean21: "さん",
    mean22: "よん / し",
    mean23: "ご",
    mean24: "１時（いちじ）",
    mean25: "５分（ごふん）",
    mean26: "１０分（じゅっぷん）",
    mean27B: "今の時刻を言う表現。",
    mean28B: "時と分を組み合わせた例文。",

     mean29: "話し手の近くの場所",
    mean30: "聞き手の近くの場所",
    mean31: "両者から離れた場所",
    mean32: "場所をたずねる言葉",
    mean33: "トイレの場所をたずねる",
    mean34: "道案内：まっすぐ",
    mean35: "右の方向",
    mean36: "左の方向",
    mean37B: "「〜はどこですか？」の例文",
    mean38B: "道案内の例文",

    mean39: "価格をたずねる言葉",
    mean40: "話し手の近くの物",
    mean41: "聞き手の近くの物",
    mean42: "遠くの物",
    mean43: "名詞と一緒に使う「この」",
    mean44: "名詞と一緒に使う「その」",
    mean45: "名詞と一緒に使う「あの」",
    mean46: "値段が低い",
    mean47: "値段が高い",
    mean48: "丁寧なお願いの表現",
    mean49B: "商品の価格をたずねる例文",
    mean50B: "商品を頼む例文",

    mean51: "食べる (たべる)",
    mean52: "飲む (のむ)",
    mean53: "行く (いく)",
    mean54: "来る (くる)",
    mean55: "見る (みる)",
    mean56: "書く (かく)",
    mean57: "読む (よむ)",
    mean58: "話す (はなす)",
    mean59B: "わたしは たべます。",
    mean60B: "あなたは のみます。",

    grammarBoxTitle: "文法ノート",
    grammarNote1: "「AもBです」は「AもBである」という意味です。",
    grammarNote2: "所有を表します。例えば「Aのかみ」は「Aの紙」です。",
    grammarNote3: "文末の丁寧語。",

    grammarBox2Title: "助詞（じょし）",
    particleHa: "は (ha) – 主題を示す。文の重要な役割。",
    particleHaExample: "わたしは学生です。 (私は学生です。)",
    particleWo: "を (wo) – 動詞の目的語を示す。",
    particleWoExample: "りんごを食べます。 (りんごを食べます。)",
    particleNi: "に (ni) – 場所・時間を示し、方向を表す。",
    particleNiExample: "学校に行きます。 (学校に行きます。)",

    grammarBox3Title: "肯定と否定の表現",
    exprSuki: "すき (suki) – 好き、気に入ること。",
    exprSukiExample: "わたしはりんごがすきです。 (私はりんごが好きです。)",
    exprKirai: "きらい (kirai) – 嫌い、好きではない。",
    exprKiraiExample: "にくがきらいです。 (肉が嫌いです。)",
    exprArimasen: "ありません (arimasen) – 否定の存在動詞。",
    exprArimasenExample: "おかねがありません。 (お金がありません。)",
    exprArimasu: "あります (arimasu) – 肯定の存在動詞。",
    exprArimasuExample: "いぬがいます。 (犬がいます。)",

    conjunctionBoxTitle: "接続詞 (せつぞくし)",
    colWord: "接続詞",
    colReading: "読み方",
    colMeaning: "意味",
    colExample: "例文",
    conj1Word: "と",
    conj1Reading: "to",
    conj1Meaning: "そして、～と一緒に",
    conj1Example: "りんごとみかんを食べます。 (りんごとみかんを食べます。)",
    conj2Word: "しかし",
    conj2Reading: "shikashi",
    conj2Meaning: "しかし、だが",
    conj2Example: "雨が降っています。しかし、出かけます。 (雨が降っていますが、出かけます。)",
    conj3Word: "だから",
    conj3Reading: "dakara",
    conj3Meaning: "だから、それで",
    conj3Example: "疲れました。だから、休みます。 (疲れました。それで、休みます。)",
    conj4Word: "それに",
    conj4Reading: "soreni",
    conj4Meaning: "その上、加えて",
    conj4Example: "宿題をしました。それに、掃除もしました。 (宿題をしましたし、それに掃除もしました。)",
    conj5Word: "けれども",
    conj5Reading: "keredomo",
    conj5Meaning: "しかし、でも",
    conj5Example: "行きたいけれども、忙しいです。 (行きたいけれども、忙しいです。)",

    linkSelam: "あいさつと基本表現",
    linkTan: "自己紹介",
    linkSayi: "数字と時刻",
    linkYer: "場所と方向",
    linkAlis: "買い物と値段の聞き方",
    linkFiil: "日常動詞",
    linkGramer: "文法ノート",
    linkPart: "助詞",
    linkOlumlu: "肯定文と否定文",
    linkBag: "接続詞",
  
  
  }
};




// Butonu göster/gizle
window.onscroll = function () {
  const btn = document.getElementById("scrollTopBtn");
  if (document.body.scrollTop > 300 || document.documentElement.scrollTop > 300) {
    btn.classList.add("show");
  } else {
    btn.classList.remove("show");
  }
};

// Yukarı kaydır
function scrollToTop() {
  window.scrollTo({ top: 0, behavior: "smooth" });
}

